name: Autograding Java Assignment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  autograde:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile Java Program
      run: |
        javac Hello.java
      continue-on-error: true

    - name: Run Java Program
      run: |
        java Hello > output.txt
      continue-on-error: true

    - name: Verify Output
      run: |
        echo "Hello java and GitHub" > expected.txt
        diff output.txt expected.txt
